### ISSUE TITLE
 analyse compositional changes (taking in account categorical and continuous covariates at the same time)

### ISSUE THREAD

**Issue by mohebg** [phipsonlab/speckle#1]
Hi, Good day, thank you for the nice package.

I have some questions on how to use propller to regress covariants as age and sex in addressing the compositional changes between case and control in scRNAseq.

In your paper you state:
"More complex experimental designs can be accommodated using the propeller.ttest and propeller.anova functions, which have the flexibility to model additional **covariates of interest, such as sex or age.**"

In your vignette, you give examples of modeling categorial covariate and continuous covariates in separate codes.

I have three levels of covariants:

- disease status (pathology vs control): which is a categorical covariate
- sex (male vs female): which is a categorical covariate
- age: is a numeric continuous covariate

Is it possible to model categorial covariates (disease status, sex), and continuous covariates (age) at the same time ? 

I have tried to model pathological status,age and sex at the same time using:
design <- model.matrix(~ 0 + PATH + pair + sex +age)

Best
Moheb

**Comment by bphipson** [comment]
Hi Moheb,

That design matrix will work fine with propeller. The way that it works is to test the first variable (ie PATH), taking into account pair + sex + age. If you're interested in getting p-values for sex or age, it requires the reformulation of the design matrix such that the factor of interest is first in the specification of the design matrix. R should automatically recognise that age is continuous as it is numeric, and disease and sex will automatically be converted to factors.

Alternatively, you can extract the transformed proportions using the getTransformedProps function and then use limma or any other linear modelling framework directly.

Hope that helps.
Cheers,
Belinda

**Comment by mohebg** [comment]
many thanks for your reply
