### ISSUE TITLE
Defining biological replicates with Speckle

### ISSUE THREAD

**Issue by reneemoerkens** [phipsonlab/speckle#3]
Hello, thank you for this nice package!

I was wondering whether I understand this correctly from the vignette (https://bioconductor.org/packages/devel/bioc/vignettes/speckle/inst/doc/speckle.html):

propeller(clusters=sce_all$cluster, sample=sce_all$sample, group=sce_all$group)

This command calculates:
- the mean proportion between biological replicates S1 and S2 (PropMean.10x) 
- the mean proportion between biological replicates S3 and S4 (PropMean.celseq) 
- the mean proportion between biological replicates S5 and S6 (PropMean.dropseq) 
- the statistical significance comparing the PropMeans of the three techniques

In my dataset the biological replicates/samples are 'cell_line1', 'cell_line2', 'cell_line3', repeated for 5 different conditions (groups). Can I just indicate in the propeller function 'sample = <Seurat_object$cell_lines>', and the function will for each of the 5 conditions (groups) calculate the mean of 'cell_line1', 'cell_line2', 'cell_line3' (for each of my clusters)?

Thank you so much!

**Comment by bphipson** [comment]
Hi,

Thanks for using the speckle package. The propeller function primarily performs a statistical test for differences in cell type proportions between groups of samples. The p-values are calculated from transformed proportions. The mean proportions for each group for each cell type is included in the output as additional statistics that may be useful in interpreting the results.

I can't fully understand your experimental design from the above description. Do you have 1 sample from cell line 1, 1 from cell line 2 and 1 from cell line 3? Or do you have multiple samples from cell line 1, cell line 2 and cell line 3? What are you trying to test? Do you just want to know what the cell type proportion differences are between the 5 conditions? If you can post the design matrix that would be helpful. 

If you only have 1 replicate from each cell line, then you would treat the three cell lines as three biological replicates, and the function will calculate the mean of the three cell lines for each of the 5 conditions for each cell type/cluster.

I hope that answers your question.

**Comment by reneemoerkens** [comment]
Hey,

Thank you for reaching out. My experiment design is like this:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/129292461/234241981-ee291ea8-120e-49a1-bcd9-87ce11aba45a.png">

Indeed, I only have 1 replicate from each cell line and the 3 different cell lines together are my biological replicates (so I want to have the mean of these). Reading your explanation, I think the propeller function works for my design. 

I will perform an ANOVA test to compare all 5 conditions at once, and I will perform T-tests to compare the conditions in pairs. Can I use the propeller function to specifically select 2 out of 5 conditions to perform a T-test or should I just subset my data before doing each comparison of 2 conditions?

**Comment by bphipson** [comment]
Hi,

If you want to specifically perform t-tests on groups of interest, please follow the vignette for detailed instructions for how to do that. It is a slightly different analysis workflow to specify the two groups you would like to test and uses the getTransformedProps function in conjunction with propeller.ttest.

The speckle package is on Bioconductor so you can easily view the vignette:
https://www.bioconductor.org/packages/release/bioc/html/speckle.html

This section of the vignette goes through an anova followed by t-tests for testing two groups:
https://www.bioconductor.org/packages/release/bioc/vignettes/speckle/inst/doc/speckle.html#fitting-linear-models-using-the-transformed-proportions-directly

Cheers,
Belinda
