### ISSUE TITLE
Is it possible to run a paired test? 

### ISSUE THREAD

**Issue by jeremymsimon** [phipsonlab/speckle#6]
Hey @bphipson! 
I have an interesting case where I have some patient data where specimens were collected pre- and post- treatment. Is it possible to run a paired test in the `speckle` framework for looking at compositional changes in a context like this? If so, how would I set that up?

Thanks!

**Comment by jonhsussman** [comment]
I too am interested in running a paired test on pre-/post treatment specimens that are paired together. That would be a highly valuable application of this approach. Thanks as well!

**Comment by bphipson** [comment]
Hi,

Yes, propeller is extremely flexible and can accommodate a paired design. Please read the vignette and you will find there is a section in there about paired designs under using the transformed proportions directly:

https://www.bioconductor.org/packages/release/bioc/vignettes/speckle/inst/doc/speckle.html 
https://www.bioconductor.org/packages/release/bioc/vignettes/speckle/inst/doc/speckle.html#fitting-linear-models-using-the-transformed-proportions-directly 

Cheers,
Belinda

**Comment by jeremymsimon** [comment]
Ack! So sorry to have missed this. Thanks Belinda!
